export const Auth = {
  AUTH_REQUEST: "AUTH/AUTH_REQUEST",
  AUTH_SUCCESS: "AUTH/AUTH_SUCCESS",
  AUTH_ERROR: "AUTH/AUTH_ERROR",
  AUTH_CREATE: "AUTH/AUTH_CREATE",
  AUTH_LOGOUT: "AUTH/AUTH_LOGOUT",
};
